### ISSUE TITLE
Generic Sign Template: large

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/tcamp#10]

**Comment by cweber** [comment]
Plan on fixing up the feet a bit, but will this meet the generic large sign needs? 

![large-signs2](https://cloud.githubusercontent.com/assets/417657/9528564/269b0042-4cc3-11e5-8e88-47be13060bd2.jpg)

**Comment by ngrad** [comment]
@cweber can you please prepare these for print? (pdf with .25in bleed)

**Comment by cweber** [comment]
Packaged for print.

transparencyCamp > 2015 > signs > large-signs Folder
