### ISSUE TITLE
Design 2015 badges

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/tcamp#7]
"Need a spot for name and organization on the front
Need schedule on the back

8am: Coffee & Registration
8:30 Opening Session
9am Lightning Talks (4: person from tech, govt, journalism, international)
9:30 Wall Setting (and ask people to intro themselves to new people [i.e., icebreaker])
10am Block 1 (already primed ahead of time)
11am Block 2
12:00 p.m. Lunch (at the round tables, designated discussion topic)
1pm Block 3
2pm Network Break (give name that implies task we want to give people)
2:30pm Block 4
3:45 Keynote Closing
4:30 End of TCamp
5:00 TCamp Happy Hour
"

**Comment by cweber** [comment]
![screen shot 2015-08-14 at 1 17 19 pm](https://cloud.githubusercontent.com/assets/417657/9279647/db015c30-4286-11e5-8d4a-8e5dfa79751b.png)

![screen shot 2015-08-14 at 1 18 11 pm](https://cloud.githubusercontent.com/assets/417657/9279665/f87ace04-4286-11e5-91ae-119854779d2c.png)

**Comment by heyitsolivia** [comment]
This is looking really great! :clap:

Not sure about the style of the sunlight foundation logo though— is that the "whitescale" version?

**Comment by cweber** [comment]
Right. Meant to mention that. InDesign does not like transparencies as copied from Illustrator. It's supposed to be the whites ale one, I just need to embed the .eps, I think.

**Comment by ngrad** [comment]
@cweber looks great! I second the logo question, looks like it's just a weird file thing. Way to go!

**Comment by cweber** [comment]
Final, save for prepping for print. (Logo is fixed, just looks janky in the tiny jpeg.)

![tcamp-badge-2015](https://cloud.githubusercontent.com/assets/417657/9529425/29505e2c-4cc8-11e5-8be8-9c95ab49d023.jpg)
![tcamp-badge-20152](https://cloud.githubusercontent.com/assets/417657/9529424/294fd7b8-4cc8-11e5-8998-c13d9886c32f.jpg)

**Comment by heyitsolivia** [comment]
Looks good to me.

:+1: :+1: :+1:

**Comment by ngrad** [comment]
@cweber these are great. Love the robot creeping above the name line.

**Comment by heyitsolivia** [comment]
Reviewing these with Scott and Jenn.

Changes:
- "Session 1, Session 2, etc" needs to be "**Block** 1, **Block** 2, etc"
- Remove leading zero's from times: change from 08:00 to **8:00**
- Combine the 8:30 and 9:00 into one time. It should say **8:30  Welcome and Lightning Talk** (similar to "Keynote & Closing Remarks")


Note: Set up Final PDFs that have bleed.

**Comment by ngrad** [comment]
@cwber can you please prepare these for print? (pdf with .25in bleed)

**Comment by cweber** [comment]
Point of clarification: Welcome and Lightning Talk(s)

Plural or not plural?

**Comment by cweber** [comment]
Packaged for print.

transparencyCamp > 2015 > badge > tcamp-badge-2015 Folder
