### ISSUE TITLE
Welcome sign

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/tcamp#8]

**Comment by cweber** [comment]
![large-signs](https://cloud.githubusercontent.com/assets/417657/9528581/4738b786-4cc3-11e5-82b5-1cddac8b1dab.jpg)

**Comment by ngrad** [comment]
@cweber can you please prepare these for print? (pdf with .25in bleed)

**Comment by cweber** [comment]
Packaged for print.

transparencyCamp > 2015 > signs > welcome-sign Folder
