### ISSUE TITLE
Generic Sign Template: small

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/tcamp#9]

**Comment by cweber** [comment]
Super open/simple for scribbling or printing whatever is needed. I think this one ties the large splashier signs in with the badges.

![small-signs](https://cloud.githubusercontent.com/assets/417657/9528606/70b9764a-4cc3-11e5-80d3-c81a502ee383.jpg)

**Comment by ngrad** [comment]
@cweber this is perfecto

**Comment by ngrad** [comment]
@cweber can you please prepare these for print? (pdf with .25in bleed)

**Comment by cweber** [comment]
Packaged for print.

transparencyCamp > 2015 > signs > small-signs Folder
